# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Build FWE

inputs:
  build-arch:
    required: true
  upload-arch:
    required: true
  extra-options:
    required: false
  dist-name:
    required: true
  cache-paths:
    required: true
  dist-files:
    required: true

runs:
  using: "composite"
  steps:
    - name: cache-deps
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: cache
        # prettier-ignore
        key: ${{ inputs.dist-name }}-${{ inputs.build-arch }}-${{ hashFiles('tools/install-deps-*.sh') }}

    - name: install-deps
      shell: bash
      run: |
        IFS=":"
        CACHE_PATHS=${{ inputs.cache-paths }}
        if [ -d cache ]; then
          for P in ${CACHE_PATHS}; do
            sudo mkdir -p `dirname ${P}`
            sudo cp -r cache${P} ${P}
          done
        fi
        sudo ./tools/install-deps-${{ inputs.build-arch }}.sh ${{ inputs.extra-options }}
        if [ ! -d cache ]; then
          for P in ${CACHE_PATHS}; do
            mkdir -p cache`dirname ${P}`
            cp -r ${P} cache${P}
          done
        fi

    - name: build
      shell: bash
      run: |
        ./tools/build-fwe-${{ inputs.build-arch }}.sh ${{ inputs.extra-options }}
        ./tools/build-dist.sh ${{ inputs.dist-files }}
        # If the output file changes, make sure to update the upload-asset job below
        mv build/aws-iot-fleetwise-edge.tar.gz build/${{ inputs.dist-name }}-${{ inputs.upload-arch }}.tar.gz
        if [ "${{ inputs.dist-name }}" == "aws-iot-fleetwise-edge-ros2" ]; then
          tar --exclude /opt/ros/galactic/include --exclude /opt/ros/galactic/cmake -zcf build/opt.tar.gz /opt/ros
        fi

    - name: unit-test
      shell: bash
      if: inputs.build-arch  == 'native'
      run: |
        PYTEST_ADDOPTS='-k "not (CANDataSourceTest or ISOTPOverCANProtocolTest or IoTFleetWiseEngineTest or OBDOverCANModuleTest or CanCommandDispatcherTest or UDSTemplateInterfaceTest)"' \
          ./tools/test-fwe.sh ${{ inputs.extra-options }}
    - name: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.dist-name }}-${{ inputs.upload-arch }}
        path: |
          build/aws-iot-fleetwise-edge
          build/iotfleetwise/aws-iot-fleetwise-edge
          build/${{ inputs.dist-name }}-${{ inputs.upload-arch }}.tar.gz
          build/Testing/Temporary/
          build/**/report-*.xml
          build/**/html_report/
          build/opt.tar.gz

    - name: upload-asset
      if: github.ref_type == 'tag'
      shell: bash
      run: |
        RELEASE_VERSION="${GITHUB_REF/refs\/tags\//}"
        gh release upload ${RELEASE_VERSION} build/${{ inputs.dist-name }}-${{ inputs.upload-arch }}.tar.gz
