#!/bin/bash
export VERSION_JSON_CPP="1.9.5"
export VERSION_PROTOBUF="3.21.12"
export VERSION_PROTOBUF_RELEASE="v21.12"
export VERSION_CURL="7.86.0"
export VERSION_CURL_RELEASE="curl-7_86_0"
export VERSION_AWS_SDK_CPP="1.11.94"
export VERSION_TINYXML2="6.0.0"
export VERSION_FOONATHAN_MEMORY_VENDOR="v1.1.0"
export VERSION_FAST_CDR="v1.0.21"
export VERSION_FAST_DDS="v2.3.4"
export VERSION_FAST_DDS_GEN="v2.0.1"
export VERSION_GOOGLE_TEST="release-1.10.0"
export VERSION_GOOGLE_BENCHMARK="v1.6.1"
export VERSION_ANDROID_CMDLINE_TOOLS="9123335"
export VERSION_ANDROID_NDK="23.1.7779620"
export VERSION_ANDROID_API="21"
export VERSION_ANDROID_SDK="33"
export VERSION_ANDROID_BUILD_TOOLS="30.0.3"
export VERSION_CMAKE="3.22.1" # Provided by Ubuntu 20.04, version here used for Android build
export VERSION_SNAPPY="1.1.8" # Provided by Ubuntu 20.04, version here used for Android build
export VERSION_OPENSSL="1.1.1s" # Provided by Ubuntu 20.04, version here used for Android build
export VERSION_BOOST="1.78.0" # Provided by Ubuntu 20.04, version here used for Android build
